language: node_js
node_js:
- '11'
sudo: false
cache:
  directories:
  - "$HOME/.npm"
script: npm run test
before_deploy:
- npm pack
deploy:
- provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: rainblock-protocol-*.tgz
  skip_cleanup: true
  on:
    branch: master
    node: '11'
    tags: true
- provider: npm
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  email: mwei@cs.ucsd.edu
  on:
    branch: master
    node: '11'
    tags: true
env:
  global:
  - secure: PWvgsHCeDDWNTfs1JTXELK7So3yNOpfa6M9CaMYdAcb7vTuoGVROUllmnpeecpMTwcc5XJDnLSKHqyqX0SrdHqzz1qguhRHH1wg0QokAT1NKUZ/TqLmUAVFGNeLJ0uMnabCw7SfPSNQxHQKet6KZV0pQbhFwVmE/iVdNEy4tBsBQZ0PopEUFAco+1igeT50ikQUz7kYMETGRUdfnLJVkKVEtymGr/q4TiE3cEGexGduNniyHuCIGQ2XhtMrTCT2/kNuSK/T/3XgC8yqsefh6aezYAnbsfFpgSJPS8Dvrb7s/xkb/I0hBrAFua1YYiG7v41b99oj/RqdgOL8eK3JZLZ5t3PlHM5O6CMXKNGEEtiV0F/3qbuJteQSuVPWTlPeHw4i9UJL2QsF6SBsvJJykQKI3/USi3PwAjV8UicDb5zBr1OkAhDIzlTZUiwsc9/89tWmu8Jd/4SHChccR8Is1K9FU4gaU+5V255p+mcM75KFbDcUEeOT5nPqijy7fga+WKGtgjjcdJOYzxOICQzwcc1AUk4ZnaypTRfLWC7AWhSh46oXzxdqZTVOEnwFOnV6a9qA028ug6uUbkD3hjnzyF171P1K1rTwK0Ew58EztqpdLp1rmG2J2+nQalhvhUyyVBjEhqtLoBcNnjz6AxMNk+hYx62pOy44kwIjJh4AOfU4=
  - secure: AAT7qtPMX0nyXLVJlN0lzIcaCfDWDHYpyoBirSxMzrlFFSSSSMHUF7GWTh/iWMNi1uHQara5BNaoMHIVfYTrhXSZ7udTHglKhmahKuJkCbvLR4aKlSeeJqLQW2Jz0S1FL7PXtxsI23UX0RTXmfe7xo78S6mkcM98pmwfLvOEhSvpYgQoPZ3+mduOf1IMyW/YsPeX2BqIVpkSyRl3gGxTSTe4psReVPfQ62bkkFNk7Kt77EE0u0FA9uUN74rsTwUS1TTfbNc2afFKJOk7IgqIXzig86q4sJeJuiYWK3yURJFLy+fPD3TNEIRia8ICcF6TzQVG94TgRIf3i+5fFIKM6N8ip67gt6R4uetwsY7rM2SfpqG+KnNj1WiFaqAxJiW6a37M4xFt8FhsXn0vXH6cw2yHH2rZz6OTSrBC140daFvvr0QlFslvbOMNVaP+5rr/RckR5DJtP1U52iVimriI/F01KMhEUOlEziCJ8d8Eg59WKHnriMKR0mUgjrj3aIykMxKwL76ZuE18gs8NcqOXz9YMGz0hSeJmOutPCCiKOgNE82/S2cP+x9+Jp5ufuFWCHghEN//odP4BByojMIIMyL95C7uRBIQYg7O3Q3dnYaMgIBgp1pZghG1oNoK5BcMnr0uU2bpx+yhVtWFhVNEQyCHpsNSOALauBFtEoSvd+PA=
