language: node_js
node_js:
- '11'
sudo: false
cache:
  directories:
  - "$HOME/.npm"
script: npm run test
before_deploy:
- npm pack
deploy:
- provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: rainblock-protocol-*.tgz
  skip_cleanup: true
  on:
    branch: master
    node: '11'
    tags: true
- provider: npm
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  email: mwei@cs.ucsd.edu
  on:
    branch: master
    node: '11'
    tags: true
env:
  global:
  - secure: jvoCBEsOfJfenzonL7KfEjjNFKUuKJ7R9bxu3eweNQX0pI/gfYGxi72rjcigd6d+OKp/HHRjlM+oI8BUuqytvlmXPqNstkhX2EkIM8q5XTlq1i6XzzjXexfictrljJu1wJPrr0bALQF+lS+JMRna4ZJj8k11VAzo9uzxxbb9Oj/qc/yOns4CUOtLBvrFQoouxQbDejhEctQY69yPL88KIjbPUneRCwQzBBEdD7kqlO9XtA/Lw4b5wU8A9+UEhXpVzKxbDX+F4Jjc4gekrHts0CuJ2x2gg0+TGc7zapiFDcrEe1rWRVE9CZOMQsne4289Kcfq0NuUa93imK3LFncWUJKrlGhAD38UqAC6ExaWLMWvQlYRfgciY91VO1Yvo1rkvom30GpCiatLSi2rkQDPTB+6OQ66VQpCGI+JUEOB+UP1qRBFLNs4d57zLslVaWYLBKWBjPAH7MJQJVIf8aFvRNDxM66Mm85nmuhorwPjpjGL5Gn4UuXkai4c41dDc52uJO0KWkxpieSl7WZGjpUD702wWcM4blU24BSxjMD3nHR3fDXtQCbBze2ti3YtsPk7OQs4fScfUjiNYnC21MIPvWzcLrRtV3yOm9nARFKlc/1Y1/G5M+YxHL5tva2+EpwEJiALjUQQ57WzRY+JuHtBILVpvtNnDmwELkLzk3GtRKE=
  - secure: vdfwgDNHSqg9JbrGejsMj4DH7z5pvRw4u0QwSUUVdaXqjtLL8LT44VrezTxjqNpvVsyW1Sz7avEeBD7cmlP9wMt+wMdV26M1eg3Sd74NEmRrUd/gI4rcMLXVdf32vtRj6LgSFHWDiKfVmeQ7QuPb7AmAzlVZyI2dHHiaQrF+3qb0y4c1ZcmdSBHc84aunz9F+w4N38SQHW6JpaD3tqfSQLVpZTEVSEBlJ+Tn3ehKmE1IKNkn/Dr1SUyt4x9OP497k8jEROuoQFA4/Qsuk2HAhGqHv/rcMx/VIqeZ5E+brBJnKy2knriJ916Qg36byVDRCVXkesrKRpdBE6aJUE1WPWT97Iwj5FhvtN+DMPCxkMa7gcmUFvGMmH3zOU/Cp58Ss/FvVTJxAtT997TXt752XVl815RUPXOgEZ5/DlFMVC/Phksqy+gUL/xrMhGTlW85T4KsQz187s5j0HDbbk7vTnekOGYXEkZW9GCn5tEHtvgEkKMdfZjtkSnLmJKmcsiI1ZSKEfK6zoYh5BH6NvUMWhDuZFNVBUfWtS2gb4xFuGfQVBaNko4lSLkoxF0fI84INrS9SFVL6iqzP27xVZdz+2CXkkR4BTTGbL6JFboT5tm+7J8TsgBxm9JCverq5RZEROyDSTqJyahLtR9td9k8REn6vRacREuRT4zQWxLps0s=
